import Foundation

struct Language: Identifiable, Hashable {
    let id: String
    let name: String

    static let all: [Language] = [
        Language(id: "auto", name: "Auto-detect"),
        Language(id: "af", name: "Afrikaans"),
        Language(id: "sq", name: "Albanian"),
        Language(id: "ar", name: "Arabic"),
        Language(id: "az", name: "Azerbaijani"),
        Language(id: "eu", name: "Basque"),
        Language(id: "bn", name: "Bengali"),
        Language(id: "be", name: "Belarusian"),
        Language(id: "bg", name: "Bulgarian"),
        Language(id: "ca", name: "Catalan"),
        Language(id: "zh-CN", name: "Chinese Simplified"),
        Language(id: "zh-TW", name: "Chinese Traditional"),
        Language(id: "hr", name: "Croatian"),
        Language(id: "cs", name: "Czech"),
        Language(id: "da", name: "Danish"),
        Language(id: "nl", name: "Dutch"),
        Language(id: "en", name: "English"),
        Language(id: "eo", name: "Esperanto"),
        Language(id: "et", name: "Estonian"),
        Language(id: "tl", name: "Filipino"),
        Language(id: "fi", name: "Finnish"),
        Language(id: "fr", name: "French"),
        Language(id: "gl", name: "Galician"),
        Language(id: "ka", name: "Georgian"),
        Language(id: "de", name: "German"),
        Language(id: "el", name: "Greek"),
        Language(id: "gu", name: "Gujarati"),
        Language(id: "ht", name: "Haitian Creole"),
        Language(id: "iw", name: "Hebrew"),
        Language(id: "hi", name: "Hindi"),
        Language(id: "hu", name: "Hungarian"),
        Language(id: "is", name: "Icelandic"),
        Language(id: "id", name: "Indonesian"),
        Language(id: "ga", name: "Irish"),
        Language(id: "it", name: "Italian"),
        Language(id: "ja", name: "Japanese"),
        Language(id: "kn", name: "Kannada"),
        Language(id: "ko", name: "Korean"),
        Language(id: "la", name: "Latin"),
        Language(id: "lv", name: "Latvian"),
        Language(id: "lt", name: "Lithuanian"),
        Language(id: "mk", name: "Macedonian"),
        Language(id: "ms", name: "Malay"),
        Language(id: "mt", name: "Maltese"),
        Language(id: "no", name: "Norwegian"),
        Language(id: "fa", name: "Persian"),
        Language(id: "pl", name: "Polish"),
        Language(id: "pt", name: "Portuguese"),
        Language(id: "ro", name: "Romanian"),
        Language(id: "ru", name: "Russian"),
        Language(id: "sr", name: "Serbian"),
        Language(id: "sk", name: "Slovak"),
        Language(id: "sl", name: "Slovenian"),
        Language(id: "es", name: "Spanish"),
        Language(id: "sw", name: "Swahili"),
        Language(id: "sv", name: "Swedish"),
        Language(id: "ta", name: "Tamil"),
        Language(id: "te", name: "Telugu"),
        Language(id: "th", name: "Thai"),
        Language(id: "tr", name: "Turkish"),
        Language(id: "uk", name: "Ukrainian"),
        Language(id: "ur", name: "Urdu"),
        Language(id: "vi", name: "Vietnamese"),
        Language(id: "cy", name: "Welsh"),
        Language(id: "yi", name: "Yiddish"),
    ]
}
